### ISSUE TITLE
Traverse all commits leading to head

### ISSUE THREAD

**Issue by dmadisetti** [juanbenitopr/python-git-wrapper#5]
Hey, so I can progress linearly down from a given head position, but it would be great to traverse the whole commit graph. Example:

![image](https://user-images.githubusercontent.com/2689338/108245284-175f2100-711e-11eb-8143-928348edf09b.png)

get to 6602230 from head.

**Comment by juanbenitopr** [comment]
Hi @dmadisetti!

Yes it looks like reasonable requests, thanks for taking the time to implementing yourself ;)

**Comment by dmadisetti** [comment]
Closed by #6 :tada:

I'm easy on the release, I'm using a local version of this until then. Thanks for the project! Dead useful
